// views/dictionary.js
// Renders a CC-CEDICT entry for a lookup term.
//
// Data source: per-character JSON shards under `dict/{firstChar}.json`,
// generated by `build/build-dict-shards.js`. The shard is fetched once
// per session (cached in lib/cache.js) and filtered for the full query term.

import { fetchJson } from '../lib/github.js';
import * as cache from '../lib/cache.js';
import { renderLookupCard, renderLookupEmpty } from '../lib/lookup-card.js';

const SHARD_CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes

/** Route-kind matcher used by `app.js`. */
export function match(route) {
    return route && route.kind === 'dictionary';
}

/** Dictionary lookups are instant — no app-first race. */
export function preferAppFirst(_route) {
    return false;
}

/**
 * Render the dictionary card for `route.term`. Falls back to an "empty"
 * card when the term has no matching entry in its shard.
 */
export async function render(route, mount, shell) {
    const term = (route && route.term) || '';
    applyChrome(shell, term);
    await renderDictCard(term, mount);
}

/**
 * Public helper used by `views/termbase.js` when it needs to fall back to
 * a dictionary lookup for the same term. Kept separate from `render` so
 * callers can drive the mount + shell independently.
 */
export async function renderDictionaryInto(term, mount) {
    await renderDictCard(term, mount);
}

/** Sets the shell title, context strip, and "Open in Read Zen" link. */
function applyChrome(shell, term) {
    if (!shell) return;
    shell.setTitle(term ? 'Dictionary · ' + term : 'Dictionary');
    shell.setContext(
        term ? `CC-CEDICT · ${term}` : 'Dictionary',
        'Chinese-English dictionary entry'
    );
    shell.hideStatus();
}

/**
 * Core lookup: load the shard for the term's first character, filter for
 * exact matches on `trad` or `simp`, and render either the full card or a
 * not-found card.
 */
async function renderDictCard(term, mount) {
    if (!term) {
        renderLookupEmpty({
            title: 'No term supplied',
            detail: 'The dictionary link is missing its term.',
            hint: 'Expected shape: #/dict/佛'
        }, mount);
        return;
    }

    // Grab the first code-point (surrogate-pair safe).
    const firstChar = [...term][0];
    if (!firstChar) {
        renderLookupEmpty({
            title: 'Invalid term',
            detail: `Could not determine the first character of "${term}".`
        }, mount);
        return;
    }

    let shard;
    try {
        shard = await loadShard(firstChar);
    } catch (error) {
        // Most common reason: no shard file for that character. Treat as
        // "no entry" from the user's perspective.
        const msg = String(error && error.message || '');
        if (msg.includes('404')) {
            renderLookupEmpty({
                title: `No dictionary entry for ${term}`,
                detail: 'CC-CEDICT has no entry for this term.',
                hint: 'Open in Read Zen to search the full corpus, termbase, and community notes.'
            }, mount);
            return;
        }
        renderLookupEmpty({
            title: 'Dictionary lookup failed',
            detail: msg || 'Unknown error while fetching the dictionary shard.'
        }, mount);
        return;
    }

    const matches = findMatches(shard, term);
    if (matches.length === 0) {
        renderLookupEmpty({
            title: `No dictionary entry for ${term}`,
            detail: `CC-CEDICT has entries for characters starting with "${firstChar}" but none match "${term}".`,
            hint: 'Open in Read Zen to search the full corpus, termbase, and community notes.'
        }, mount);
        return;
    }

    renderLookupCard(buildCard(term, matches), mount);
}

/**
 * Fetch a shard JSON from `dict/{char}.json`, cached in-memory.
 * The character is percent-encoded so CJK works regardless of the server's
 * URL handling.
 */
async function loadShard(char) {
    const cacheKey = 'dict-shard:' + char;
    const cached = cache.get(cacheKey);
    if (cached) return cached;

    const url = 'dict/' + encodeURIComponent(char) + '.json';
    const shard = await fetchJson(url);
    cache.set(cacheKey, shard, SHARD_CACHE_TTL_MS);
    return shard;
}

/** Return all entries in the shard whose `trad` or `simp` equals the term. */
function findMatches(shard, term) {
    if (!Array.isArray(shard)) return [];
    const out = [];
    for (const entry of shard) {
        if (!entry) continue;
        if (entry.trad === term || entry.simp === term) {
            out.push(entry);
        }
    }
    return out;
}

/**
 * Build the shared-card payload for one or more matching entries. Multiple
 * entries are merged into a single card: one per pinyin reading, definitions
 * collected as a bulleted list.
 */
function buildCard(term, matches) {
    // Use the first entry as the canonical title source.
    const primary = matches[0];
    const allPinyin = matches
        .map((m) => m && m.pinyin)
        .filter(Boolean);
    const uniquePinyin = Array.from(new Set(allPinyin));

    const allDefs = [];
    for (const m of matches) {
        if (m && Array.isArray(m.defs)) {
            for (const d of m.defs) {
                if (d && !allDefs.includes(d)) allDefs.push(d);
            }
        }
    }

    const sections = [];
    if (uniquePinyin.length > 0) {
        sections.push({
            heading: 'Pronunciation',
            content: uniquePinyin.join(' · ')
        });
    }
    if (allDefs.length > 0) {
        sections.push({
            heading: 'Definitions',
            content: allDefs
        });
    }

    // Variant forms: show simp + trad if they differ for any entry.
    const variants = new Set();
    for (const m of matches) {
        if (m && m.trad && m.simp && m.trad !== m.simp) {
            variants.add(`${m.trad} (traditional) · ${m.simp} (simplified)`);
        }
    }
    if (variants.size > 0) {
        sections.push({
            heading: 'Variants',
            content: Array.from(variants)
        });
    }

    return {
        title: primary && primary.trad ? primary.trad : term,
        subtitle: uniquePinyin[0] || '',
        sections,
        footer: 'Source: CC-CEDICT'
    };
}
